### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by fengmk2** [cnpm/npminstall#1]
https://docs.npmjs.com/cli/install

- [x] global install (`-g, --global`)
- [x] postinstall script
  - [x] support Windows
- [x] node-gyp
  - [x] node-pre-gyp
- [x] bin (yo@1.6.0, fsevents@1.0.6)
- [x] scoped package
- [x] bundleDependencies / bundledDependencies (node-pre-gyp@0.6.19, fsevents@1.0.6)
- [x] optionalDependencies (pm2@1.0.0)
- [x] peerDependencies (co-defer@1.0.0, co-mocha@1.1.2, estraverse-fb@1.3.1)
- [x] deprecate message
- [x] `--production` mode
- [x] cleanup when install failed
- all types of npm package
  - [x] a) a folder containing a program described by a package.json file (`npm install file:eslint-rule`)
  - [x] b) a gzipped tarball containing (a) (`npm install ./rule.tgz`)
  - [x] c) a url that resolves to (b) (`npm install https://github.com/indexzero/forever/tarball/v0.5.6`)
  - [x] d) a <name>@<version> that is published on the registry with (c)
  - [x] e) a <name>@<tag> (see npm-dist-tag) that points to (d)
  - [x] f) a <name> that has a "latest" tag satisfying (e)
  - [x] g) a <git remote url> that resolves to (a) (`npm install git://github.com/timaschew/cogent#fix-redirects`)
- [x] `save`, `save-dev`, `save-optional`

**Comment by fengmk2** [comment]
```
npa('foo@https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e')
Result {
  raw: 'foo@https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e',
  scope: null,
  name: 'foo',
  rawSpec: 'https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e',
  spec: 'https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e',
  type: 'remote' }
```

**Comment by fengmk2** [comment]
```
[fsevents@1.0.6] scripts.install: "node-pre-gyp install --fallback-to-build"
sh: 1: node-pre-gyp: not found
```

**Comment by dead-horse** [comment]
```
[fsevents@1.0.6] scripts.install: "node-pre-gyp install --fallback-to-build"
sh: 1: node-pre-gyp: not found
```

fixed in https://github.com/cnpm/npminstall/commit/98211df7a365a8007b2cebc8a997d9730e276ef8

**Comment by fengmk2** [comment]
Great!

**Comment by fengmk2** [comment]
How about windows?

**Comment by fengmk2** [comment]
Why we need peerDeps https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by fengmk2** [comment]
https://github.com/npm/npm/issues/6565#issuecomment-74971689

![image](https://cloud.githubusercontent.com/assets/156269/12866976/e6fc39cc-cd1b-11e5-9235-e0e9581d089d.png)

**Comment by fengmk2** [comment]
```
npm WARN peerDependencies The peer dependency mocha@>=1.20.0 included from grunt-mocha-test will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
