### ISSUE TITLE
安装常用的冒号分割的 Url 出错

### ISSUE THREAD

**Issue by magicdawn** [cnpm/npminstall#107]
## git url
see https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a

```
git clone ssh://[user@]host.xz[:port]/path/to/repo.git/
git clone [user@]host.xz:path/to/repo.git/
```

## npm deps
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

npm 支持使用上述这两种
```
"module1":  "git+ssh://[user@]host.xz[:port]/path/to/repo.git/",
"module2": "git+ssh://[user@]host.xz:path/to/repo.git/"
```

## 现象

- gitlab url 为 `git@xxxx.com:user/project.git`
- package.json 为

    ```json
    { dependencies: { "module": "git+ssh://git@xxxx.com:user/project.git" } }
    ```

### 安装结果

- npm 是可以安装的
- cnpm 安装出错, 可以看到报错为 `sh -c git clone ssh://git@xxxx.com:user/project.git`

其实应该运行的命令是 `sh -c git clone git@xxxx.com:user/project.git`

## 解决

1. 不使用 `:` 分割的路径, 改为 `git@xxxx.com:user/project.git` -> `git@xxxx.com/user/project.git`  即可
2. 这里应该是 npm 处理了, cnpm 没有处理, 但是冒号`:`分隔比较常用, 所以来报个bug

**Comment by fengmk2** [comment]
@magicdawn 来提个 pr 修复一下？

**Comment by lovelope** [comment]
使用 cnpm 安装私有仓库的 gitlab 包出错。示例链接如下：
```json
{
  "dependencies": {
    "module": "git+http://gitlab+deploy-token-1:TOKEN@gitlab.private.com/user/repo.git#v1.2.3"
  }
}
```
