### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by afc163** [cnpm/npminstall#121]
master 分支：http://github.com/ant-design/ant-design
操作：`tnpm install`

```
[antd-tools@0.8.9] scripts.postinstall success, use 72ms
[antd@1.11.0] scripts.prepublish: "antd-tools run guard"
antd-tools run guard

/Users/afc163/Projects/ant-design/node_modules/.0.3.7@orchestrator/index.js:153
			throw err;
			^
1
Error: Run "sh -c antd-tools run guard" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/tnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.2.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js --tmp=/Users/afc163/.tnpm_tmp --progress=false --no-proxy --disturl=https://x/dist/node --userconfig=/Users/afc163/.tnpmrc --registry=http://registry.npm.x.com -d --china --prefix=/usr/local --forbidden-licenses=AGPL,CPAL,OSL --custom-china-mirror-url=https://x/dist
```

```
$ tnpm -v
tnpm@4.10.4 (/usr/local/lib/node_modules/tnpm/bin/tnpm.js)
npm@3.10.7 (/usr/local/lib/node_modules/tnpm/node_modules/npm/lib/npm.js)
node@5.12.0 (/usr/local/bin/node)
npminstall@2.2.1 (/usr/local/lib/node_modules/tnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local (load prefix from: $ npm config get prefix)
darwin x64 15.5.0 
registry=http://registry.npm.x.com
```

**Comment by fengmk2** [comment]
http://github.com/ant-design/ant-design 慢速 clone 中

**Comment by fengmk2** [comment]
@afc163 node_modules/.0.3.7@orchestrator/index.js:154 跑了异常，err 竟然是数字 `1` ... 不知道什么情况。通过 `./node_modules/.bin/antd-tools run guard` 运行可以重现。

![image](https://cloud.githubusercontent.com/assets/156269/18461781/8c8fec72-79af-11e6-8fb9-e890a2fb8e99.png)

**Comment by fengmk2** [comment]
antd-tools 依赖了 `process.env.npm_config_argv` 导致的。https://github.com/ant-design/antd-tools/blob/master/lib/utils/get-npm-args.js#L8

我去看看 npm_config_argv 环境变量的定义。

**Comment by ziluo** [comment]
+1

**Comment by fengmk2** [comment]
> process.env.npm_config_argv {"remain":[],"cooked":["run","prepublish"],"original":["run","prepublish"]}

**Comment by fengmk2** [comment]
使用的是这个模块 nopt https://github.com/npm/nopt/blob/10a750c9bb99c1950160353459e733ac2aa18cb6/lib/nopt.js#L43

**Comment by fengmk2** [comment]
- https://github.com/npm/npm/blob/9e03561547ec5830c5f61caa4e6221d4d3b813aa/bin/npm-cli.js#L42
- https://github.com/npm/npm/blob/master/lib/config/defaults.js#L226

```js
var conf = nopt(types, shorthands)
npm.argv = conf.argv.remain
```

定义太多，我还是简单模拟一下 nopt 好了。

**Comment by fengmk2** [comment]
npm 连 argv 都搞这么复杂。。。

**Comment by fhqdgv** [comment]
现在依然报错
`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! antd@2.7.1 dist: `antd-tools run dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@2.7.1 dist script 'antd-tools run dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     antd-tools run dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\test\ant-design\npm-debug.log
`

**Comment by fengmk2** [comment]
@fhqdgv cnpm -v 显示的是什么版本呢？怎样重现？

**Comment by fengmk2** [comment]
@fhqdgv https://github.com/ant-design/ant-design/issues/3143#issuecomment-279606678 测试没问题的

**Comment by fhqdgv** [comment]
谢谢回复  应该不是cnpm问题，刚试了直接npm install也是同样的问题，可能是windows的原因
npm run dist后报错Error: spawn atool-build ENOENT
然后改了
`function runCmd(cmd, _args, fn) {
  const args = _args || [];
  const runner = require('child_process').spawn('cmd', ['/s', '/c', cmd, '-o', 'short'], args, {
    // keep color
    stdio: 'inherit',
    env: getRunCmdEnv(),
  });
  // const runner = require('child_process').spawn(cmd, args, {
  //   // keep color
  //   stdio: 'inherit',
  //   env: getRunCmdEnv(),
  // });

  runner.on('close', (code) => {
    if (fn) {
      fn(code);
    }
  });
}`
再npm run dist才报的这个错npm ERR! Exit status 1
