### ISSUE TITLE
local install --production 模式下, prepublish 不应该被执行

### ISSUE THREAD

**Issue by yibn2008** [cnpm/npminstall#122]
在 npmjs.com 的文档中:

> prepublish: Run BEFORE the package is published. (Also run on local npm install without any arguments.)

在 npminstall 里, 已经过滤掉了 `install <pkg>` 的情形, 但对于 `--production` 模式, 也是需要过滤的, 请参见 npm 的讨论: https://github.com/npm/npm/issues/3059#issuecomment-32057292

**Comment by fengmk2** [comment]
ok， @yibn2008 要尝试帮忙修复吗？
