### ISSUE TITLE
tnpm update 无效

### ISSUE THREAD

**Issue by afc163** [cnpm/npminstall#132]
源上有满足条件的新版本，但本地文件未更新。

**Comment by fengmk2** [comment]
- 不支持 tnpm update，请使用 `rm -rf node_modules && tnpm i` 代替。
- 内部可以考虑将 update 替换成这两个步骤。

**Comment by fengmk2** [comment]
`npminstall update` => `rm -rf node_modules &&  npminstall`

**Comment by afc163** [comment]
... tnpm update 的运行效率要高多了。

**Comment by fengmk2** [comment]
不行的，这样还得去遍历整个树，还不如删除了重新安装。
