### ISSUE TITLE
how to use with proxy

### ISSUE THREAD

**Issue by p2227** [cnpm/npminstall#135]
I had read this issue https://github.com/cnpm/npminstall/issues/33
but it didn't work

I simply read the source code but didn't find any lines about proxy.

**Comment by fengmk2** [comment]
```bash
$ http_proxy=http://localhost:8008 npminstall -c
```

not work?

**Comment by fengmk2** [comment]
confirm not support now. I will done this today.

**Comment by fengmk2** [comment]
https://github.com/kdzwinel/betwixt/blob/master/README.md
