### ISSUE TITLE
comparison with yarn

### ISSUE THREAD

**Issue by hax** [cnpm/npminstall#136]
It seems [yarn](https://github.com/yarnpkg/yarn) has many similar design of npminstall...

**Comment by fengmk2** [comment]
We don't have lockfile.

**Comment by fengmk2** [comment]
yarn install tips is great!

```
[1/4] 🔍  Resolving packages...
warning egg-mock > mm > thenify > native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
warning egg-ci > nunjucks > chokidar > fsevents > node-pre-gyp > npmlog > gauge > has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
```

**Comment by fengmk2** [comment]
- [1/4] 🔍  Resolving packages...          => get package meta and building flat tree in memory
- [2/4] 🚚  Fetching packages...           => download tgz and up pack it
- [3/4] 🔗  Linking dependencies...      => copy files to node_modules base on flat tree
- [4/4] 📃  Building fresh packages...  => save logfile

**Comment by fengmk2** [comment]
@hax Why npminstall is fast because we are using link file avoid the flat tree build step.

**Comment by fengmk2** [comment]
https://zhuanlan.zhihu.com/p/22892675

**Comment by dead-horse** [comment]
还是不喜欢 shrinkwrap 或者 lock 的方式，按照现在 npm 的这种依赖规模，想不出 lock 比按照 semver 自动更新有什么优势。

**Comment by fengmk2** [comment]
lock 就不做了，要 lock 的直接使用 yarn 就好了，但是 yarn 的各种 tips 和 ux 可以学习改进。

**Comment by hax** [comment]
我个人自己的项目是不用lock的，但是公司的大项目用lock感觉还是很正常的。@dead-horse 你们内部不用lock么？

**Comment by dead-horse** [comment]
不 lock 的，保持模块更新和修复的快速，如果发现外部依赖的模块有问题，直接在内部的 registry 上将有问题的模块先临时处理一下（设置 latest tag 或者其他方式）。

这个方式跑着还是很稳定的，少数几次外部依赖模块有 bug 也是发现后先在 registry 上处理掉了，也不会出现发到线上发现安装的版本不对（因为发上线的代码包在上线前有一轮预发测试的）。

**Comment by fengmk2** [comment]
@hax 不 lock，因为我们会在开发阶段结束后，进入集成测试阶段，在集成测试阶段会打包，然后生产环境直接发布这个打好的包，不会重新 npminstall 的。
