### ISSUE TITLE
Link from cache dir and save disk store

### ISSUE THREAD

**Issue by fengmk2** [cnpm/npminstall#148]
We can link all node_modules from cache dir on local development env.

**Comment by fengmk2** [comment]
http://weibo.com/1640328892/EdA1ZqDjy?type=comment

**Comment by dead-horse** [comment]
最开始就想过全部 link 到一个目录下，问题是一旦中间安装错误，影响会比较大，可能要删除所有本地模块重装了

**Comment by fengmk2** [comment]
哦，对，里面有一个核心问题无解。

**Comment by fengmk2** [comment]
我们是无tree的
