### ISSUE TITLE
遇到 getaddrinfo ENOTFOUND 问题

### ISSUE THREAD

**Issue by popomore** [cnpm/npminstall#152]
不确定是否是问题，在 travis 和 appvoyer 都遇到这个问题，按道理 dns 不应该会有问题，难道是 node6 的 bug？

https://ci.appveyor.com/project/eggjs/egg-core/build/1.0.141

**Comment by popomore** [comment]
https://travis-ci.org/eggjs/egg-core/jobs/170108216

**Comment by fengmk2** [comment]
DNS 请求太快了，估计是npm registry没有返回keeplaive导致的

**Comment by popomore** [comment]
加一层 dns 缓存？

**Comment by fengmk2** [comment]
嗯，加一下好了。

**Comment by popomore** [comment]
这个准备做在哪？

先查一下 dns，如果获取了 ip 就使用 ip 请求，否则走原来逻辑。

**Comment by fengmk2** [comment]
先 dns.lookup 找到 ip，再请求。

**Comment by fengmk2** [comment]
https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L111 custom dns lookup 只支持 http，https 还不知道如何覆盖。。。

**Comment by popomore** [comment]
单独 lookup，然后传 ip 和 host 进去？

**Comment by fengmk2** [comment]
不行的，https 比较特殊。我先对 agent 的 maxSockets 设置一个上限20，这样就不会大量 dns lookup 了 https://nodejs.org/api/http.html#http_agent_maxsockets

**Comment by popomore** [comment]
恩，现在这个错比较常见
