### ISSUE TITLE
electron-packager hangs when dealing with cnpm installed node_modules

### ISSUE THREAD

**Issue by TooBug** [cnpm/npminstall#155]
When install node modules with cnpm, and then use electron-packager to package electron app, electron-packager hangs. The template folder size is keep increasing and never end.

Maybe has something to do with the soft link file structure that cnpm uses.

**Comment by fengmk2** [comment]
will be fix after https://github.com/electron/electron-rebuild/pull/183 merged

**Comment by wenshiqi0** [comment]
It may not. The situation is different. I'll fix it later. @fengmk2
