### ISSUE TITLE
npminstall 安装时，未使用项目中的node版本

### ISSUE THREAD

**Issue by hugohua** [cnpm/npminstall#180]
在project中，依赖了node 5.x，然后电脑中的node版本是6.x。

在安装node-sass的时候，会报如下错误。

![](http://img3.tbcdn.cn/5476e8b07b923/TB1nKySOVXXXXX3apXXXXXXXXXX)

估计原因是因为 npminstall的时候，没有使用项目中的node版本导致。npm install没有这个问题。

**Comment by fengmk2** [comment]
> 在project中，依赖了node 5.x

你设怎样配置这个依赖的？npm 还有这种功能？

**Comment by hugohua** [comment]
package.json 里面有这么一段

```
"engines": {
    "install-node": ">=4.0.0 <6.0.0"
  },
```

**Comment by fengmk2** [comment]
install-node 是谁实现的？

**Comment by fengmk2** [comment]
fixed inside.

**Comment by hugohua** [comment]
高效回复，点赞！
