### ISSUE TITLE
install material-design-icons very slow

### ISSUE THREAD

**Issue by fengmk2** [cnpm/npminstall#183]
```bash
npminstall material-design-icons
```

**Comment by fengmk2** [comment]
32MB 
![image](https://cloud.githubusercontent.com/assets/156269/22095400/534d55bc-de4f-11e6-9f24-126766592f98.png)

**Comment by fengmk2** [comment]
解压 material-design-icons-3.0.1.tgz 文件都卡死了。。。 cpu 100%

**Comment by fengmk2** [comment]
解压出来有 356MB ...

![image](https://cloud.githubusercontent.com/assets/156269/22095443/aa56de5a-de4f-11e6-9577-c24f65e6c025.png)

**Comment by coolme200** [comment]
都是图。。。

**Comment by fengmk2** [comment]
https://registry.npm.taobao.org/material-design-icons/latest 可以在这里下载
