### ISSUE TITLE
完全遵循 semver 安装还是在 semver 基础上考虑祖先模块版本

### ISSUE THREAD

**Issue by dead-horse** [cnpm/npminstall#196]
现在已经有两个特例了：* 和 1.x 形式的都会先从 root 去找合适的。如果这类需求确实是前端必须要的，那 npminstall 就按照 npm 一样来实现好了。

两种不同的选择：

1. 完全遵循 semver 原则，各个模块独立安装自身依赖。（有利于 node 运行环境，不需要考虑体积问题）
2. 在遵循 semver 的原则下，尽可能合并模块版本。（有利于前端）

> the ~ prefix says "match any patch version greater than or equal to the one I specified"

按照上面 [npm 的人对 semver 的解释](https://github.com/npm/npm/issues/11887#issuecomment-201615642)，`~1.1.0` 并不保证一定安装到符合这个规则的最新版本。但是一定是使用到符合这条规则的版本。

npm 的安装策略如下：

```sh
root/
  koa@1.1.0
  mod/
    koa@~1.1.0

root/
  koa@1.1.0
  mod/
    koa@^1.1.0
# 上面两个依赖树安装到的 koa 版本都是 1.1.0

root/
  koa@~1.1.0
  mod/
    koa@^1.1.0
# 上面依赖树安装到的 koa 版本都是 ~1.1.2

root/
  mod/
    koa@^1.1.0
  moe/
    koa@~1.1.0
# 上面依赖树会安装两个不同版本的 koa
```

在选择第二种的情况下，如果 node 的模块都开放引用（例如都用 ^），和完全遵循 semver 原则没有区别。当然反过来也是一样的，但是目前来看，前端模块能遵循 semver 的不多。

**Comment by dead-horse** [comment]
我倾向于在没有更好的解决方案之前先按照第二种方式实现，原因：

1. 对于可以完全开放式引用的项目而言（例如 egg），两种方式没有区别
2. npm 已经是按此方式实现，这个不同点可能造成更多的特例产生，例如 https://github.com/cnpm/npminstall/issues/192 中，如果 ` @types/react-dom` 将依赖改成了 `@types/react@^15`
3. 前端确实存在此类需求，在无法保证所有的模块都遵循 semver 原则的情况下，需要由一个统一的父模块对底层依赖进行一定的约束。
4. 即使是完全遵循 semver 原则，低版本的模块依旧会被引入，也不能完全达到 semver 自动升级修复 bug 的目的。

**Comment by dead-horse** [comment]
@fengmk2 @afc163

**Comment by afc163** [comment]
我肯定是支持第二种方式的，即尽可能修复任何 npm 支持但是 tnpm 会导致出错的问题，最好 npminstall 能直接去跑 npm 已有的用例。

---

> 前端确实存在此类需求，在无法保证所有的模块都遵循 semver 原则的情况下，需要由一个统一的父模块对底层依赖进行一定的约束。

这个确实是前端经常使用的做法。

**Comment by fengmk2** [comment]
`^` 依赖不赞成走这种方式，会导致 semver 完全失效

**Comment by fengmk2** [comment]
而且不会想第二种方式那样预期，有 root 能搞定。例如一个模块 a 在tree 里面出现了好多个 minor 版本，而 root 里面是最新的 minor，那么并没有解决任何问题。还是会有大量的 a 重复。

**Comment by fengmk2** [comment]
> 前端确实存在此类需求，在无法保证所有的模块都遵循 semver 原则的情况下，需要由一个统一的父模块对底层依赖进行一定的约束。

其实应用开发者无法解决的，他不可能知道整棵树的模块有多少，只能解决他遇到问题的模块。

**Comment by dead-horse** [comment]
先将这个模式实现一下，以  antd 和 egg 做样例来试试看看两类应用的差距。后面再决定是否通过参数来开启。
