### ISSUE TITLE
spwan npminstall 进程的时候，安装成功信息往stderr里面输出

### ISSUE THREAD

**Issue by Jirapo** [cnpm/npminstall#210]
when I spwan a process to exec a task.js ,
task.js
`co(function* () {
yield npminstall(options);
}).catch((err) => {
console.error(err.stack);
})`
 
if pacakges installed succeed, terminal would output some messages :
`
✔ Installed 3 packages 
✔ Linked 2 latest versions 
✔ Run 0 scripts 
✔ All packages installed (5 packages installed from npm registry, used 520ms, speed 39.39kB/s, json 5(20.48kB), tarball 0B) 
`
these were  'stderr' messages not 'stdout' messages, I was so confused by it.
in souce code:
`options.spinner.succeed(`Installed ${tasks.length} packages`);`
I hope it add some options to output in 'stdout';

> 'ora' api
stream
Type: WritableStream
Default: process.stderr
Stream to write the output.

**Comment by dead-horse** [comment]
options 可以传递 `options.console` 来自定义日志输出。
