### ISSUE TITLE
Install fail! Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by gbk** [cnpm/npminstall#224]
我有一个在线构建服务，在 npminstall 的时候偶发会出现这样的错误，可能是什么原因呢？

✖ Install fail! Error: EEXIST: file already exists, symlink '../../.npminstall/._@ali_vc-table-pc@4.1.3@@ali/vc-table-pc' -> '/tmp/vire/task-0e0eb5a8-019f-41ed-8804-f4d1bc6125e0/node_modules/@ali/vc-table-pc'

alinode v2.1.0
npminstall 2.16.4

```js
yield npminstall({
    pkgs,
    storeDir: `${workDir}/.npminstall`,
    targetDir: workDir,
    root: process.cwd(),
    registry: 'http://registry.npm.alibaba-inc.com',
    cacheDir: null,
    timeout: 5 * 60000,
});
```

workDir 每次构建都会 uuid 重新创建

**Comment by gbk** [comment]
发现原因了，用户同一个依赖不同的版本，定义了两次。

**Comment by creamidea** [comment]
这个补充一下，pkgs 这个参数里面出现了同名的组件，但是这个组件的版本还不一样，导致安装失败。
