### ISSUE TITLE
Support shrinkwrap ?

### ISSUE THREAD

**Issue by gbk** [cnpm/npminstall#226]
我们使用 npminstall 进行云构建，底层依赖的版本不可控，出现过好几次因为底层依赖更新造成的错误导致线上故障。
希望 npminstall 能够支持 shrinkwrap，这样可以在项目提测后锁死所有依赖的版本号。
或者，有没有什么替代方案？

**Comment by dead-horse** [comment]
https://zhuanlan.zhihu.com/p/22934066

保证你们的构建系统发布和测试用同一个包就好了。
