### ISSUE TITLE
Rename `await` in code

### ISSUE THREAD

**Issue by tommytroylin** [cnpm/npminstall#233]
We found an issue when we try to bundle npminstall.
Since `await` is a reserved keyword in es6 strict mode,  it throws an error.

Please solve it [here](https://github.com/cnpm/npminstall/blob/f25b3049a03edc5ccd81483f283614e9bd782d66/lib/format_install_options.js#L6) and [here](https://github.com/cnpm/npminstall/blob/f25b3049a03edc5ccd81483f283614e9bd782d66/lib/format_install_options.js#L23) and also upgrade to `await-event@2`.

Thank you.

**Comment by fengmk2** [comment]
@tommytroylin Can you send a pull request to fix it?
