### ISSUE TITLE
npminstall don't work at mocha

### ISSUE THREAD

**Issue by atian25** [cnpm/npminstall#237]
```bash
$ git clone mochajs/mocha
$ npminstall
```

![image](https://user-images.githubusercontent.com/227713/26907270-04c9c3d2-4c25-11e7-9f81-033a7df1f20e.png)

**Comment by dead-horse** [comment]
难道他的 package.json 里面的名字和模块名不一样？我试试

**Comment by dead-horse** [comment]
他写的依赖是 ` "karma-sauce-launcher": "coderbyheart/karma-sauce-launcher"`，这个 git 的模块名已经改成了 ` @coderbyheart/karma-sauce-launcher"。

- npm5 的表现是不安装这个模块但不报错
- yarn 的表现是安装这个模块
- npminstall 的表现是不安装这个模块并且报错

我改成提示但不报错吧，

**Comment by fengmk2** [comment]
呃。。。震惊
