### ISSUE TITLE
安装 antd 出错

### ISSUE THREAD

**Issue by alex-mm** [cnpm/npminstall#258]
初步分析是依赖包里的 react-slick 里有个  `"postinstall": "opencollective postinstall"`
![image](https://user-images.githubusercontent.com/3302053/36021939-4e12cee4-0dc2-11e8-8a0e-ffb627416475.png)

npminstall@3.3.0
antd@^3.2.0
node@6.12.2
tnpm@5.8.0 

@fengmk2

**Comment by fengmk2** [comment]
最好参考我们的参数如何生成的 https://github.com/cnpm/npminstall/blob/master/bin/install.js#L211

非 cli 方式调用，都需要将很多环境参数传递齐全的。

**Comment by alex-mm** [comment]
@fengmk2 知道了，是我们使用的问题，多谢。
