### ISSUE TITLE
Question : why did you not PR the ied repository 

### ISSUE THREAD

**Issue by kevincaradant** [cnpm/npminstall#28]
Hi

Your repository is great :) ,  i met one problèm about the timeout random during the npminstall which change everytime.  Not on the same dependancies .   Also i ask me why you d ont do a PR at ied repository ?  Maybe some contributors can help you to increase the features and fix some bugs :).  This repository has a really potential ')

**Comment by dead-horse** [comment]
This project is aimed at replace npm's install command and we don't use `ied` for now.

What's your problem about timeout? Can you provide a detailed description?

**Comment by kevincaradant** [comment]
This is one example : 

```
[babel-core@6.5.2] install error: RequestError: connect ETIMEDOUT 42.120.63.172:443 (req "error"), G                                                                                                                                         ET https://registry.npm.taobao.org/debug/%3E%3D2.1.1%20%3C3.0.0 -1 (connected: false, keepalive sock                                                                                                                                         et: false)
headers: {}, parentDir: C:\Users\kevin\Desktop\wt3, remove C:\Users\kevin\Desktop\wt3\node_modules\.                                                                                                                                         npminstall\babel-core\6.5.2\babel-core\.tnpminstall.done
error stack: Error: connect ETIMEDOUT 42.120.63.172:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
RequestError: connect ETIMEDOUT 42.120.63.172:443 (req "error"), GET https://registry.npm.taobao.org                                                                                                                                         /debug/%3E%3D2.1.1%20%3C3.0.0 -1 (connected: false, keepalive socket: false)
headers: {}
Error: connect ETIMEDOUT 42.120.63.172:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
```

**Comment by dead-horse** [comment]
https://github.com/cnpm/npminstall/blob/master/bin/install.js#L59 @fengmk2 change registry to https://registry.npmjs.com/ ?

**Comment by kevincaradant** [comment]
Thank you :).   i think that resolve my problem. But sometimes, https://registry.npm.taobao.org works and sometimes not. Why do you use an other registry by default ? Maybe : https://registry.npmjs.com/  will be better no ?

**Comment by fengmk2** [comment]
@dead-horse yep, make https://registry.npmjs.com registry be default will be better.

**Comment by fengmk2** [comment]
@kevincaradant please upgrade to 1.0.8.

**Comment by kevincaradant** [comment]
ok that work. I opened an other issue, i thought that was about this issue but finally it's not link.
