### ISSUE TITLE
Randomly miss some packages

### ISSUE THREAD

**Issue by maxime1992** [cnpm/npminstall#30]
Hi,

first of all thank for all your work it's a really nice project !

I'm wondering why I need to install twice sometimes, it's like npminstall do not see some packages at first run.

For example, if I clone one of my repo : https://github.com/maxime1992/web-template

Then inside it I run `npminstall` and run `npm run dev` it says "recess" is not installed. I run again `npminstall` and it works. I start from a fresh install and then it says it cannot find a sass module.

I also have some errors with phantomJS : 
![image](https://cloud.githubusercontent.com/assets/4950209/13380918/56f0424e-de4e-11e5-87f3-236865ec526a.png)

If I'm missing anything I would be glad to know.

Cheers :)

**Comment by fengmk2** [comment]
@maxime1992 Please upgrade to npminstall@1.1.0 and retry again.

**Comment by maxime1992** [comment]
I gave a try and it seems that it perfectly works !
I only have one problem with my test (due to phantomjs) but I need to figure out if it's from me or from the install. It could be because of the recent change of repo (phantomjs-built if I remember well) but not sure.

I'll have a look when I come home :)
