### ISSUE TITLE
any possible to disable spinners

### ISSUE THREAD

**Issue by kaelzhang** [cnpm/npminstall#302]
Sometimes `npminstall` is integrated into another library, and we don't want any outputs including spinners, traces, and details.

But spinner could not be disabled because of [here](https://github.com/cnpm/npminstall/blob/master/lib/format_install_options.js#L20)

Is it ok to change the code to

```js
options.spinner = options.spinner === null || options.spinner === false
  // spinners are explicitly disabled by user
  ? null
  :  options.detail 
    ? null
    : ora();
```

**Comment by fengmk2** [comment]
you can redirect the stdout and stderr to handle outputs.
