### ISSUE TITLE
(async () => {  Unexpected token (

### ISSUE THREAD

**Issue by AppianZ** [cnpm/npminstall#314]
![image](https://user-images.githubusercontent.com/15190615/69823331-86afd300-1243-11ea-9706-62166763bfb8.png)

当我在服务器上构建的时候，会出现这个问题，今天早上构建的时候发现的，昨天下午还ok

**Comment by fengmk2** [comment]
latest 已经切换 3.x，你的 node 版本已经很老的，请升级到 node 8，或者 node 10 吧。
