### ISSUE TITLE
Working under proxy ?

### ISSUE THREAD

**Issue by maxime1992** [cnpm/npminstall#33]
I wanted to see if V1.1.0 fixed this issue : https://github.com/cnpm/npminstall/issues/30

But now I have this : 
![image](https://cloud.githubusercontent.com/assets/4950209/13395455/197d4d98-deef-11e5-8a6e-204fb1ba4872.png)

Hint : I tried that command at work and there's a proxy.
I think I might have to set `strict-ssl=false`, is that possible ?

**Comment by dead-horse** [comment]
looks like the same issue https://github.com/npm/npm/issues/9580

**Comment by maxime1992** [comment]
Indeed, do you read. npmrc too ? 
"As a workaround you can turn ssl checking off in your .npmrc
strict-ssl=false"
Or is there another file for npminstall ?

**Comment by dead-horse** [comment]
please try #36 to see if this branch has fixed your problem?

**Comment by fengmk2** [comment]
@maxime1992 please use npminstall@1.2.1 take a try.
