### ISSUE TITLE
执行cnpm install 从私库安装包时请求头未携带authorization header信息

### ISSUE THREAD

**Issue by huangbowen521** [cnpm/npminstall#337]
首先cnpm config set registry=https://packages.aliyun.com/5e6f6c4115eccd0001c1fe87/npm/npm-registry 一个私库；
然后 cnpm login，使用私库的用户名和密码登录。
执行 cnpm view MODULE_NAME等命令正常，但执行cnpm install命令返回401错误，经查是因为cnpm install命令请求头中未携带authorization认证信息。

**Comment by fengmk2** [comment]
@huangbowen521 欢迎来贡献实现

**Comment by suzhengda** [comment]
同样

**Comment by xiejesses** [comment]
这么久过去了，有解决方法吗

**Comment by fengmk2** [comment]
需要带上认证 header -H 'authorization: Bearer xxx'，我今天实现一下。
