### ISSUE TITLE
当模块使用时不支持--save那种的吗

### ISSUE THREAD

**Issue by Asarua** [cnpm/npminstall#340]
如题

**Comment by gemwuu** [comment]
提供下可复现示例。

**Comment by Asarua** [comment]
就是正常情况下不是有

```bash
cnpm i axios -S
```

这种的吗
然后我看见这个模块是有提供`global`配置，但是并没有暴露出类似于`save`、`save-dev`之类的选项

**Comment by gemwuu** [comment]
> 就是正常情况下不是有
> 
> ```shell
> cnpm i axios -S
> ```
> 
> 这种的吗
> 然后我看见这个模块是有提供`global`配置，但是并没有暴露出类似于`save`、`save-dev`之类的选项

支持的，可以试下。
