### ISSUE TITLE
how to support --save or --save-dev

### ISSUE THREAD

**Issue by plane-hjh** [cnpm/npminstall#350]
![image](https://user-images.githubusercontent.com/28526327/127595336-7e0d563f-d6d6-4eae-8114-8b4f847de98a.png)
in this config, i dont know how to config it,can you give some examples?

**Comment by gemwuu** [comment]
the `--save` or `--save-dev` options are supported on argv only, there is not js config api. see [L399](https://github.com/cnpm/npminstall/blob/c85e54ade239a161bc5e8a60c99f3be3117a433c/bin/install.js#L399)
