### ISSUE TITLE
node-gyp@4.0.0 › request@^2.87.0 request has been deprecated

### ISSUE THREAD

**Issue by younth** [cnpm/npminstall#364]
deprecate › npminstall@4.11.0 › node-gyp@4.0.0 › request@^2.87.0 request has been deprecated, see https://github.com/request/request/issues/3142
deprecate › npminstall@4.11.0 › node-gyp@4.0.0 › request@2.88.2 › har-validator@~5.1.3 this library is no longer supported

官方升级下吧

**Comment by fengmk2** [comment]
closed by https://github.com/cnpm/npminstall/pull/385
