### ISSUE TITLE
Run "sh -c git checkout template" error, exit code 128

### ISSUE THREAD

**Issue by wangxv** [cnpm/npminstall#368]
使用git+ssh://git@gitlab.xxx.cn:xxxx.git#template安装时报错
![image](https://user-images.githubusercontent.com/30195186/139771644-26c4d64a-1d6e-4f9f-86c2-e55f3f6c499c.png)

**Comment by wangxv** [comment]
@killagu

**Comment by wangxv** [comment]
version: 4.10.0

**Comment by gemwuu** [comment]
update npminstall to 5.x. #370  fix this.
