### ISSUE TITLE
支持 libc 版本配置

### ISSUE THREAD

**Issue by fengmk2** [cnpm/npminstall#386]
https://dev.to/arcanis/yarn-32-libc-yarn-explain-next-major--o22

**Comment by fengmk2** [comment]
https://github.com/npm/rfcs/pull/519#issuecomment-1033800667

**Comment by fengmk2** [comment]
https://github.com/swc-project/swc/blob/a564ced26a814cf1f696b04ab121638ffb3e77b1/scripts/npm/linux-x64-gnu/package.json#L15-L17

**Comment by fengmk2** [comment]
https://github.com/yarnpkg/berry/pull/3981

**Comment by fengmk2** [comment]
https://github.com/yarnpkg/berry/pull/3981/files#diff-f9ba955128e960171ac97ce06b0b0a940bb074af2794429a9f03c75f2a3bd459R20

**Comment by fengmk2** [comment]
使用 https://nodejs.org/dist/latest-v16.x/docs/api/report.html 来获取 libc 的类型。

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/159143462-1c5d58ac-e0ee-4c75-bc76-7be9652a7ee4.png)

**Comment by fengmk2** [comment]
@hyj1991 libc family 也支持了。

**Comment by hyj1991** [comment]
> @hyj1991 libc family 也支持了。

赞，npm 无 mirror 化可以研究下怎么搞了

**Comment by yisibl** [comment]
The libc field is also supported by pnpm: https://github.com/pnpm/pnpm/issues/4454

**Comment by fengmk2** [comment]
厉害了，实时标准。
