### ISSUE TITLE
How to fix Unauthenticated cannot download pkg from github package or azure feeds

### ISSUE THREAD

**Issue by JohnHuang-CT** [cnpm/npminstall#396]
as title , it can't success download and throw 401

**Comment by JohnHuang-CT** [comment]
Or how to specify npmrc

**Comment by fengmk2** [comment]
Any logs?

**Comment by JohnHuang-CT** [comment]
> Any logs?

What I mean is how to Use as Lib to download packages locally from a private repository

**Comment by JohnHuang-CT** [comment]
- npminstall doesn't seem to support @scope 
- azure's auth uses cookies not jwt `Basic xxx` https://github.com/cnpm/npminstall/blob/6.2.0/lib/get.js#L53
