### ISSUE TITLE
ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time

### ISSUE THREAD

**Issue by xzblog** [cnpm/npminstall#416]
I got a warning when using npminstall: ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time

because npminstall rely on undici
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/24378347/191403837-79ae9f13-c38c-4274-85d4-4af5d0b6ced1.png">

This warning is displayed every time I run the command, which disturbes me. I hope it can be fixed

**Comment by fengmk2** [comment]
What's the node version?

**Comment by xzblog** [comment]
> What's the node version?

node : v16.11.0
npm : 8.0.0

**Comment by fengmk2** [comment]
@xzblog update node to 16.18.0
