### ISSUE TITLE
不支持读取.npmrc配置

### ISSUE THREAD

**Issue by hoivee** [cnpm/npminstall#423]
希望npminstall在安装依赖的时候支持读取[.npmrc](https://docs.npmjs.com/cli/v8/configuring-npm/npmrc)配置

**Comment by albert-cai** [comment]
+1

**Comment by fengmk2** [comment]
请问使用的 npminstall 版本是多少？

**Comment by hoivee** [comment]
> 请问使用的 npminstall 版本是多少？

之前用的 6.5.2，升级到  6.6.1 试了下，依旧不行

**Comment by xiejesses** [comment]
使用最新的 6.6.2 版本也不行

**Comment by fengmk2** [comment]
如果是认证 token，会在 https://github.com/cnpm/npminstall/pull/432 支持。
