### ISSUE TITLE
RFC: npminstall rapid install 模式的优化

### ISSUE THREAD

**Issue by Beace** [cnpm/npminstall#427]
**首先感谢 rapid install 的发明，作为受益者和首批使用者想提出一些更多的可能。**

## 容错

1. 安装失败后的容错性
目前安装失败后，重新安装 `nydus` 的挂载以及 `overlay` 等不会 `umount`，`nydus` 重复 `mount` 会导致文件错乱，`node_modules` 乱码，`postinstall` 失败。`overlay` 会重复多层挂载，后续清理比较困难。

```ts
try {
  await install(params)
} catch (err) {
  await cleanProject();
  throw err;
}
```

## 优化
1. 增加一份服务端 mock 的 API 接口实现
虽然示例中给出了一个 `local arborist` 生成的例子，但是既然提出了服务端预构建加速的环节，还是期望能够单纯的提供一份 API 或者 mock 接口到规范或者文档里说明。
2. npm 参数的透传
服务端经常会遇到历史的 lock 文件处理 peer deps 的问题，期望支持类似的 `legacy-peer-deps` 参数，能够兼容 npm 原生参数的用法 比如：`npminstall --fs=rapid  --legacy-peer-deps`
3. 支持多次 install
目前的实现，多次 `npminstall --fs=rapid`，多次 install 不会提前检查是否 mount，而是多次 mount，挂载多层。类似容错性第一条。

## 扩展
1. 最大可能的在其他包管理器场景应用
如何兼容其他包管理器，比如 npm 无 fuse 场景下如何尽可能的利用预构建以及并发下载 tarball 的能力，以提升原生 npm 的性能。

**Comment by fengmk2** [comment]
https://github.com/cnpm/rapid
