### ISSUE TITLE
Bug: jpegtran-bin not found

### ISSUE THREAD

**Issue by kevincaradant** [cnpm/npminstall#44]
Hi 

I come with a little bug : 

![image](https://cloud.githubusercontent.com/assets/6093175/13557301/098563e0-e3ee-11e5-9ee4-89f4488e86ed.png)

This module is not found. But the installation have not error.
This problem seems to be only on Windows ...

Any idea guys ? :) 

Thank you

**Comment by dead-horse** [comment]
please try remove node_modules and reinstall.

**Comment by kevincaradant** [comment]
Try twice, but its the same thing :/

**Comment by dead-horse** [comment]
can you provide your install command or `package.json` ?

**Comment by kevincaradant** [comment]
{
  "dependencies": {
    "angular": "1.5.0",
    "angular-animate": "1.5.0",
    "angular-loading-bar": "0.8.0",
    "angular-mocks": "1.5.0",
    "angular-sanitize": "1.5.0",
    "angular-translate": "2.9.2",
    "angular-translate-loader-static-files": "2.9.2",
    "angular-ui-bootstrap": "1.2.0",
    "angular-ui-router": "1.0.0-alpha0",
    "angular-ui-router-anim-in-out": "1.0.2",
    "bootstrap": "3.3.6",
    "font-awesome": "4.5.0",
    "ng-webworker": "github:mattslocum/ng-webworker",
    "rx": "4.0.8",
    "rx-angular": "1.1.3"
  },
  "devDependencies": {
    "babel-core": "6.5.2",
    "babel-preset-es2015": "6.5.0",
    "babel-runtime": "6.5.0",
    "connect": "3.4.1",
    "conventional-github-releaser": "1.1.0",
    "critical": "0.7.0",
    "del": "2.2.0",
    "ghooks": "1.0.3",
    "git-semver-tags": "1.1.2",
    "gulp": "https://git@github.com/gulpjs/gulp.git#4.0",
    "gulp-angular-embed-templates": "2.2.0",
    "gulp-autoprefixer": "3.1.0",
    "gulp-babel": "6.1.2",
    "gulp-browserify": "0.5.1",
    "gulp-bump": "1.0.0",
    "gulp-complexity": "0.3.2",
    "gulp-concat": "2.6.0",
    "gulp-concat-css": "2.2.0",
    "gulp-connect": "2.3.1",
    "gulp-conventional-changelog": "1.1.0",
    "gulp-cssnano": "2.1.1",
    "gulp-decomment": "0.1.3",
    "gulp-flatten": "0.2.0",
    "gulp-gh-pages": "0.5.4",
    "gulp-git": "1.7.0",
    "gulp-gzip": "1.2.0",
    "gulp-htmlmin": "1.3.0",
    "gulp-if": "2.0.0",
    "gulp-imagemin": "2.4.0",
    "gulp-inject": "3.0.0",
    "gulp-karma-runner": "1.1.9",
    "gulp-load-plugins": "1.2.0",
    "gulp-ng-annotate": "2.0.0",
    "gulp-ngdocs": "0.2.13",
    "gulp-notify": "2.2.0",
    "gulp-plumber": "1.1.0",
    "gulp-preprocess": "2.0.0",
    "gulp-rename": "1.2.2",
    "gulp-replace": "0.5.4",
    "gulp-rev": "7.0.0",
    "gulp-sass": "2.2.0",
    "gulp-sass-lint": "1.1.1",
    "gulp-series": "1.0.2",
    "gulp-size": "2.0.0",
    "gulp-sourcemaps": "1.6.0",
    "gulp-strip-debug": "1.1.0",
    "gulp-uglify": "1.5.3",
    "gulp-uncss": "1.0.4",
    "gulp-util": "3.0.7",
    "gulp-xo": "0.8.0",
    "gulp-zip": "3.2.0",
    "imagemin-pngquant": "4.2.2",
    "jasmine": "2.4.1",
    "jasmine-core": "2.4.1",
    "jpegtran": "0.2.0",
    "jpegtran-bin": "3.0.6",
    "jsonfile": "2.2.3",
    "karma": "0.13.19",
    "karma-coverage": "0.5.3",
    "karma-jasmine": "0.3.6",
    "karma-phantomjs-launcher": "1.0.0",
    "less": "2.6.0",
    "marked": "0.3.5",
    "merge2": "1.0.1",
    "node-notifier": "4.5.0",
    "node-sass": "3.4.2",
    "opn": "4.0.0",
    "path": "0.12.7",
    "plato": "1.5.0",
    "recess": "1.1.9",
    "serve-static": "1.10.2",
    "validate-commit-msg": "2.1.0",
    "xo": "0.12.1",
    "yargs": "4.2.0"
  }
}

**Comment by fengmk2** [comment]
@kevincaradant I install pass on OSX, I think this maybe some thing got wrong on Windows.

![image](https://cloud.githubusercontent.com/assets/156269/13639348/4facadd8-e64b-11e5-9781-011fc5af2b2e.png)

**Comment by kevincaradant** [comment]
Yes but it seems with a normal npm install It works.

Here, it's not the case. I'm going to try again and i will say you if it's a problem only on npminstall or not with Windows

**Comment by kevincaradant** [comment]
OK npm install --no-optional => Works

npminstall V1.4.1 => no works with the same problem about jpegtran :/

**Comment by kevincaradant** [comment]
Any news about my problèm ? :)

**Comment by dead-horse** [comment]
Hi, does this problem still exists in the latest version of npminstall(2.0.0-beta.2)?

**Comment by kevincaradant** [comment]
no, it's seems to be fixed at least V1.8 ;). We can closed this issue. i didin't see this open issue ;)
