### ISSUE TITLE
npminstall will install package in current directory, different behaviour with origin npm

### ISSUE THREAD

**Issue by XGHeaven** [cnpm/npminstall#46]
such as follow structure

```
a
    - node_modules
    - b
```

In `b` directory, I run `npm install connect` which will install `connect` into `a/node_modules`, But `npminstall install connect` will install `connect` into `a/b/node_modules`

**Comment by dead-horse** [comment]
I think this is a more nature way than what npm dose.

**Comment by fengmk2** [comment]
go to a and npm install
