### ISSUE TITLE
使用rollup@rollup/plugin-commonjs插件，打包遇到npminstall()时解析报错

### ISSUE THREAD

**Issue by L0821** [cnpm/npminstall#467]
报错提示：(plugin commonjs--resolver) SyntaxError: The keyword 'package' is reserved (233:12) in C:\Users.\..\node_modules\npminstall\lib\local_install.js

npminstall/lib /local_install.js 223行 package标识符被识别成关键字了，给package取个别名吧

**Comment by fengmk2** [comment]
js 运行并没有报错。

**Comment by L0821** [comment]
![image](https://github.com/cnpm/npminstall/assets/89029291/90c53fe1-7b85-4702-bfad-4df589cace9b)
rollup的commonjs--resolver打包npminstall({root:process.cwd(),pkgs: [{ name: 'foo', version: '~1.0.0' }]})
