### ISSUE TITLE
Not working on repo with commit hash

### ISSUE THREAD

**Issue by livelazily** [cnpm/npminstall#51]
Sample package.json:
```json
{
  "name": "test_hash",
  "dependencies": {
    "grunt-cli": "gruntjs/grunt-cli#121f282"
  }
}
```

**Comment by dead-horse** [comment]
支持这种模式会导致所有从 git 安装都会很慢（因为要 clone 整个项目才能找到这个 commit），而且从 git 的一个 commit 安装也很不靠谱，所以 npminstall 暂时不会去对这个做支持

**Comment by livelazily** [comment]
可否使用 github 的 api 直接下载指定 commit 的 archive:
https://github.com/foo/bar/archive/commit-hash.zip 

这样就不用下载整个 repo 了
因为使用这种依赖的大都不是自己直接使用, 而是依赖树上的某个包, 偶尔引用某个包时就会踩坑了

**Comment by dead-horse** [comment]
你直接写 https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e

不要写 git 协议

**Comment by dead-horse** [comment]
#52

**Comment by livelazily** [comment]
问题主要是依赖定义不是自己写的, 而是某个依赖的依赖的依赖等等, 这个不好直接到上游去修改

**Comment by dead-horse** [comment]
@ibigbug 会解决这个问题，合并到 #52

**Comment by ibigbug** [comment]
嗯，在处理了。
