### ISSUE TITLE
npminstall gitbook@2.0.0 failed

### ISSUE THREAD

**Issue by ibigbug** [cnpm/npminstall#52]
* https://github.com/GitbookIO/gitbook/blob/2.0.0/package.json#L16
* https://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/1.7.10.txt#n84

`git clone -b commit-hash` fails on some repository

**Comment by dead-horse** [comment]
直接把 git 下载变成从 https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e 这个地址下载 tar 包，如果下载不到再 clone 整个项目
