### ISSUE TITLE
windows global path error

### ISSUE THREAD

**Issue by dead-horse** [cnpm/npminstall#55]

**Comment by fengmk2** [comment]
我修复一下？

**Comment by fengmk2** [comment]
> Global installs on Unix systems go to {prefix}/lib/node_modules. Global installs on Windows go to {prefix}/node_modules (that is, no lib folder.)

https://docs.npmjs.com/files/folders#node-modules

**Comment by fengmk2** [comment]
> When in global mode, executables are linked into {prefix}/bin on Unix, or directly into {prefix} on Windows.

https://docs.npmjs.com/files/folders#executables
