### ISSUE TITLE
without `npm_execpath` in pre/post install script

### ISSUE THREAD

**Issue by XGHeaven** [cnpm/npminstall#56]
I install `dtrace-proivde`, error occur cause by no `npm_execpath` in `install` script runtime.

origin `npm` would add `npm_execpath` in runtime env, but `npminstall` not.

[npm npm_execpath source](https://github.com/npm/npm/blob/2005f4ce11f6cdf142f8a77f4f7ee4996000fb57/lib/utils/lifecycle.js#L68)

**Comment by dead-horse** [comment]
提供一下 dtrace-provide 的 install 脚本，这个模块搜不到？

**Comment by XGHeaven** [comment]
@dead-horse https://github.com/chrisa/node-dtrace-provider/blob/master/scripts/install.js
