### ISSUE TITLE
node 6 下 npminstall 的 cache 不行了

### ISSUE THREAD

**Issue by hax** [cnpm/npminstall#73]
见：https://github.com/nodejs/node/pull/5950#issuecomment-215048458

赶紧让他们在 6.0.1 里 revert 掉。

ied和pnpm也都一样。

**Comment by fengmk2** [comment]
这下要死了。。。

**Comment by hax** [comment]
https://github.com/nodejs/node/issues/3402#issuecomment-215166795 这个comment很强。。。看来势必是要revert的了。

**Comment by hax** [comment]
悲剧：https://github.com/nodejs/node/issues/3402#issuecomment-215201672

**Comment by hax** [comment]
看来已经决定要revert了：https://github.com/nodejs/node/pull/6537

**Comment by dead-horse** [comment]
👍

**Comment by hax** [comment]
FYI: https://github.com/nodejs/node/issues/10107

建议快去review一下，不要再出幺蛾子了。
