### ISSUE TITLE
Find a way to impl flat mode

### ISSUE THREAD

**Issue by fengmk2** [cnpm/npminstall#74]
Maybe it will slow as npm3 does.

**Comment by kevincaradant** [comment]
Hi 

Do you want impl like npm 3 in flat mode with node 6 ?  Because npm is really slow.  Even in node 6, and the weight of libs in my case is twice bigest than before :/.  The powerfull of your lib is the time to install the libraries,  I hope you don t want something slow like npm  3 ').

**Comment by dead-horse** [comment]
@kevincaradant wait [this issue](https://github.com/nodejs/node/issues/3402) have a conclusion.

**Comment by kevincaradant** [comment]
Oh OK sorry,   I was afraid when I saw,  slow like npm 3 :).

**Comment by fengmk2** [comment]
@kevincaradant Maybe we can close this issue after node v6 support symlink realpath.

**Comment by fengmk2** [comment]
https://github.com/nodejs/node/pull/6537
