### ISSUE TITLE
tnpm ii 无法更新到版本

### ISSUE THREAD

**Issue by hugohua** [cnpm/npminstall#93]
tnpm ii react-router@2.4.1  装的是 2.4.1 这个版本。
装完后，我更新组件  用的命令是  tnpm ii react-router@^2.4.0
理论上，装的应该是react-router@2.5.2 这个版本， 但实际上装的还是2.4.1

如果我把node_modules 删掉，重新用tnpm ii react-router@^2.4.0 安装，这样就能正常安装到2.5.2 这个版本了。  

使用:

```
 tnpm ii react-router  
 tnpm ii react-router@2.5.2 
```
这两个命令都是可以的
![image](https://cloud.githubusercontent.com/assets/1908773/16540258/57dd5a58-4090-11e6-9174-67fc79cf9d7d.png)

**Comment by fengmk2** [comment]
@hugohua 重新安装 tnpm 即可。
